package com.eventable

import android.os.Bundle
import android.view.View
import androidx.fragment.app.Fragment
import androidx.navigation.fragment.findNavController
import kotlinx.android.synthetic.main.fragment_home.*


class HomeFragment : Fragment(R.layout.fragment_home) {

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        NothingBtn.setOnClickListener{//philbruck:HomeFragmentDirections ist ne autogenerated Kalsse vom safeArgs plugin
            var variable_1 = HomeFragmentDirections.actionHomeFragmentToInvitationFragment() //philbruck: nutzen der action aus dem navGraph
            findNavController().navigate(variable_1) //philbruck mit safeargs hat man auch per compilezeit die sicherheit das es funktioniert

        }

    }


}