package com.eventable

import android.os.Bundle
import android.view.View
import androidx.fragment.app.Fragment
import androidx.navigation.fragment.findNavController
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import kotlinx.android.synthetic.main.fragment_home.*


class HomeFragment : Fragment(R.layout.fragment_home) {

    private var layoutManager: RecyclerView.LayoutManager? = null
    private var adapter: RecyclerView.Adapter<RecyclerAdapter.ViewHolder>? = null

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        /*NothingBtn.setOnClickListener {//philbruck:HomeFragmentDirections ist ne autogenerated Kalsse vom safeArgs plugin
            var variable_1 =
                HomeFragmentDirections.actionHomeFragmentToData1Fragment() //philbruck: nutzen der action aus dem navGraph
            findNavController().navigate(variable_1) //philbruck mit safeargs hat man auch per compilezeit die sicherheit das es funktioniert

        }*/

        layoutManager = LinearLayoutManager(activity) //philbruck: hier wird die activity übergeben weil man ja eine Context übergebn muss und Fragmnet leiter nicht von Context ab!
        recyclerView.layoutManager = layoutManager

        adapter = RecyclerAdapter()
        recyclerView.adapter = adapter

    }


}